### ISSUE TITLE
Animations are now jumpy since i upgraded to 3

### ISSUE THREAD

**Issue by Sazira** [jquery/api.jquery.com#1001]
Ever since i upgraded JQuery to version 3 all my animations (show(), fade(), slide(), etc) have become jumpy/not smooth. The upgrade guide says:

> The code that jQuery uses to show and hide elements has been updated to focus on inline rather than computed styles, respecting stylesheet display values whenever possible for increased compatibility with responsive design techniques (in which active stylesheet rules can dynamically change upon device reorientation/window resize/etc.). As a result, disconnected elements are no longer considered hidden unless they have inline display: none, and therefore .toggle() will no longer differentiate them from connected elements as of jQuery 3.0.

> Further, while .show() and similar calls will continue to force visibility of elements that are hidden by stylesheet rules, supporting this functionality slows down all show/hide operations and its use is not recommended. The determination of which display value to set in such cases has also been simplified, defaulting to "block" when body-level rules hide elements by type.

> Any code expecting hidden elements to be reshown with their previous computed display styles, or disconnected elements to treated as hidden, should be reviewed. The team created a table of all the possibilities related to the display state and show/hide actions in order to minimize the setting of non-empty inline styles.

This still doesn't tell me how to fix my animations...

**Comment by gibson042** [comment]
The best advice we can give is not to rely on jQuery overriding cascade-inherited `display: none`, instead hiding animated elements solely with inline styles (at least at the time of `.show()`/`.slide()`/etc.).

**Comment by Sazira** [comment]
My styles are inline! I use JQuery to hide stuff before showing them so those styles are always inline! Why did you close this?? I still don't have a solution!

**Comment by kswedberg** [comment]
@Sazira : this isn't the place bug reports or requests for help. This is the repo for the the API _documentation_. A more appropriate place would probably be stackoverflow.com

**Comment by Sazira** [comment]
@kswedberg Stackoverflow isn't giving me any answeres either. This post is about an issue in the API documentation so I think I'm in the right place.

So basically what you're telling me is that JQuery ruined all effects and animations and all I can do is go back to JQuery 2??

**Comment by timmywil** [comment]
@Sazira The problem hasn't been pinpointed yet. Feel free to open an issue at https://github.com/jquery/jquery/issues with a test case and we can take a closer look.

**Comment by Sazira** [comment]
> The problem hasn't been pinpointed yet

@timmywil does that mean someone's working on it?

**Comment by timmywil** [comment]
@Sazira No, it means that we don't know what to work on. The problem is currently too vague. "My animations are broken" is not a bug report. We need it to be as specific as possible in order for us to come up with a solution. For instance, if the problem was "animations noticeably slow down due to the use of rAF", we would definitely look at that. Right now, we don't if the problem is in your code (whether it be the way you are creating animations or something else) or if there actually is a problem in jQuery. jQuery 3 does have some breaking changes, but we can't give specific advice without having a test case that illustrates your problem. Usually, we recommend these vague problems be flushed out on stackoverflow, the jQuery forums, or in the #jquery irc channel because we are all volunteers that don't necessarily have the time to provide that kind of support. That said, you have much better chance of getting us to make an exception for you if you had a test case from jsfiddle.net or jsbin.com that we can investigate. If you decide to put that together, post it on the jQuery repo (not here). Thanks.

**Comment by kswedberg** [comment]
@Sazira , I'm sorry you're having a problem with animations in jQuery 3, and I hope @timmywil's comment provides enough guidance for you to direct your issue to the appropriate venue. Just for the record, though, the upgrade guide you reference is in the [jquery.com repo](https://github.com/jquery/jquery.com/), not the api.jquery.com repo.
