### ISSUE TITLE
Not able to edit demo codes in API pages so I can see the impact.

### ISSUE THREAD

**Issue by shyamji1983** [jquery/api.jquery.com#1028]
I am looking for this feature in jQuery/ jQuiryUI site from long time, but still it is not available. I am not able to edit code of demos, so I can change the live code and can see the impact. In this way I can learn jquery easily & quickly. 

Alternatively you can also provide external links for users like link to CodePen /JSBin /JSfiddle or any other site you prefer.

Now it is time to add this feature in your API pages's demo code.

Thanks

**Comment by dmethvin** [comment]
That is a great idea but also quite a bit of work. Would you be able to do the work on it?

**Comment by shyamji1983** [comment]
Can you or anyone guide me how it will be implemented. Sure I can also contribute to implement this.

**Comment by dmethvin** [comment]
Deciding how to implement it would be part of the work. There's no reason to create another bin-like web site to run the code so most likely we'd need to find one of the bin sites that could handle the traffic and wanted to work with us.

**Comment by mgol** [comment]
Wasn't the plan to cooperate with jsbin on that?
-- 
Michał Gołębiowski

**Comment by dmethvin** [comment]
@mgol Yes there was some discussion that jsbin would be a good partner, but nothing came of it since we didn't have anyone taking on the project. 

It seems like the rough outline would be:

1) Determine which bin-like site has both the interest and the capacity to handle our examples. CodePen and jsbin are probably at the top of my list.
2) Figure out the technical implementation. Would we iframe the examples, or just link to their site? How would we do ongoing updates, would they still live in our repo?
3) Move the examples. Exactly how that's done would most likely depend on how we do ongoing updates.

**Comment by shyamji1983** [comment]
We should keep examples on jquery.com own pages, as user will only click on external bin (codepen / jsbin) link if they want to play with the given example code.

**Comment by dmethvin** [comment]
I doubt this will happen given the amount of work it involves. If someone wants to volunteer to do the work we can reopen.
