### ISSUE TITLE
jQuery() is missing a signature

### ISSUE THREAD

**Issue by salamutoo** [jquery/api.jquery.com#1060]
_jQuery(selector, selector)_ is allowed
description for _context_ in _jQuery(selector [,context])_ should be _Selector or Element or jQuery_
instead of _Element or jQuery_

[http://api.jquery.com/jQuery/](http://api.jquery.com/jQuery/)

**Comment by dmethvin** [comment]
Although that signature "works" if you trace the code, there's no reason to use it.

**Comment by aried3r** [comment]
Hey! Sorry to dig up this old issue, but could you maybe elaborate on this a bit, @dmethvin? We're migrating an old code base to TypeScript and found very few occurrences of this, e.g. `$("li", "ul")` (example code, we don't actually do *that*).

However the type definitions don't allow that, [see here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3e1e03d0d43d9cf569c93e27c8763e2e94a6674c/types/jquery/JQueryStatic.d.ts#L140). I couldn't find any information about this being unsupported, deprecated or discouraged. There's [even a test for it](https://github.com/jquery/jquery/blob/3edfa1bcdc50bca41ac58b2642b12f3feee03a3b/test/unit/selector.js#L54). This issue is the only place I could find a mention of this.

While it's trivial to fix these occurrences to something that is either a an Element or jQuery, I'd love to update the type definitions in case others also migrate their jQuery code base, but I have to provide sources, and as it stands the documentation and the source code don't match.

Thanks!

**Comment by mgol** [comment]
@aried3r Thanks for the update.

Since we even have tests for this and we support a lot of similar parts of this API, I don't see a reason to not document it. Let's discuss it at the next meeting.

**Comment by timmywil** [comment]
As long as we test it, I'm not opposed to documenting it.

**Comment by timmywil** [comment]
@dmethvin @gibson042 What do you think?

**Comment by dmethvin** [comment]
My dislike for the `$(elem, root)` signature is just that it's the same as `$(root).find(elem)` which is a lot more obvious in my opinion. It's unlikely that we will ever remove it, but I'm not sure why anyone would choose to use it except for obfuscation. So I suppose we can document it similar to `$("td").ready(fn)` which I doubt we could ever remove as well.

**Comment by mgol** [comment]
@dmethvin I get that it's cleaner to do `$(root).find(elem)` but we already document `$(elem, root)` for a lot of types so that battle is lost & I'd rather be consistent here. What do you think?

**Comment by gibson042** [comment]
I also dislike the signature, but am in favor of documenting it.

**Comment by mgol** [comment]
PR: #1169.
