### ISSUE TITLE
Changes in 1.9 regarding .attr() are not mentioned in .attr() documentation

### ISSUE THREAD

**Issue by teo1978** [jquery/api.jquery.com#1129]
Prior to 1.9.0, `.attr()` would in some cases still return the value of the property rather than the attribute, while starting from 1.9.0, `.attr()` consistently returns the initial value of the attribute for any attribute, unlike `prop()`.
For example, prior to 1.9.0, `.attr("value")` returns the same as `.prop("value")` and `.val()`, while starting from 1.9.0 they differ.

This is explained at https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-, but there's no mention of it whatsoever at https://api.jquery.com/attr/#attr-attributeName, and there should be.

**Comment by sunilkumarvalmiki** [comment]
can i take the  issue,

**Comment by mgol** [comment]
Sure, PRs are welcome.

**Comment by AurelioDeRosa** [comment]
Are you sure this isn't mentioned? In the documentation page we have:

> Before jQuery 1.6, the .attr() method sometimes took property values into account when retrieving some attributes, which could cause inconsistent behavior.

**Comment by teo1978** [comment]
Nope, I'm talking about this:
> However, versions up to 1.9 continued to support using .attr() for specific situations.

which is mentioned here: https://jquery.com/upgrade-guide/1.9/#attr-versus-prop-
but not here: https://api.jquery.com/attr/#attr-attributeName

This changed in 1.9, not 1.6

**Comment by dmethvin** [comment]
The documented recommendation as of 1.6 was to use `.prop()` rather than `.attr()`. The fact that we let deprecated usage continue until 1.9 shouldn't be a factor. 

At this point in 2019 I think we should only focus on incorrect docs for the most recent 1.x, 2.x, or 3.x rather than attempting to document the behaviors and bugs of each version from years past. That would make the docs very hard to read and there's no particular reason why someone should be stuck, for example, on 1.8.1 and expect us to document every deviation from past or subsequent behavior.
