### ISSUE TITLE
Please indicate VCS revision in use

### ISSUE THREAD

**Issue by Chealer** [jquery/api.jquery.com#1130]
Issue #1125 has supposedly been fixed 2 months ago. Yet, api.jquery.com still shows a broken version. It is not clear whether api.jquery.com is just using an old Git revision, or if the source was not properly fixed.

Please add an indication of the Git revision in use on api.jquery.com. Usually, that is done at the bottom of pages. It would be even better if the area used to display that information linked to the Git repository.

**Comment by mgol** [comment]
Thanks for bringing the stale content issue to our attention. The most recently added tag is what gets published to https://api.jquery.com. I forgot to add a new tag after merging the PR, sorry for that. It should be fixed now.

We plan to migrate away from this XML-based repo using a heavily customized WordPress to GitHub pages managed directly from the jQuery repository similarly to how https://api.qunitjs.com/ migrated. It will be easier to contribute as the pages will most likely be written in Markdown and, hence, readable directly from GitHub.

Because of that, I don't think we'll invest more time in the current setup, including showing the version number. But it'll take us time to migrate to the new solution.

**Comment by Chealer** [comment]
Thanks for the information @mgol .
Why was this report closed?

**Comment by mgol** [comment]
@chealer I explained that in the last paragraph of my reply.

**Comment by Chealer** [comment]
@mgol , so basically you are saying this was an exception due to a mistake and should not happen again?

**Comment by mgol** [comment]
A mistake may always happen. All I'm saying is our docs infrastructure will most likely be rebuilt completely (the new one may not even rely on specific versions) and we don't want to invest more time in the existing ones.

We do content updates so that the docs are up to date but we don't plan to spend much time on infrastructure.

A PR can be accepted but remember this may not carry over to the new docs.
