### ISSUE TITLE
$.ready documentation

### ISSUE THREAD

**Issue by PikadudeNo1** [jquery/api.jquery.com#205]
[Ticket #11470](http://bugs.jquery.com/ticket/11470) brought a ready promise to jQuery 1.8, but it's not in the API docs yet.

**Comment by arthurvr** [comment]
PR https://github.com/jquery/api.jquery.com/pull/530.

**Comment by dmethvin** [comment]
I still don't think we should document `jQuery.ready.promise()` because that implies `jQuery.ready` is a `jQuery.Deferred`-like object with a `.promise()` method. Instead, I'd like to document that `jQuery.ready` is accepted as a deferred/promise in APIs such as `jQuery.when()`. The distinction is subtle perhaps, but means is that someone could exclude `jQuery.Deferred` but put in their own `jQuery.ready` implementation based on, for example, a native `Promise`, but still maintain decent interoperability. Does that seem sane?

**Comment by gibson042** [comment]
I agree with that approach. The method is essentially an internal implementation detail for enabling things like `jQuery.when( jQuery.ready )` or (hopefully) `Promise. resolve( jQuery.ready )`.

**Comment by dmethvin** [comment]
The blueprint for exposing the ready promise is set [in this comment](https://github.com/jquery/jquery/issues/1778#issuecomment-72764833) by @gibson042. Basically, we're not documenting it to be a `jQuery.Deferred` but instead a thenable that is generally compatible with other promise mechanisms including `jQuery.when` and the standard `Promise.resolve`. I've updated the title of this issue to reflect that.

**Comment by dmethvin** [comment]
Also note that this approach is back-compatible so we can document it for existing versions and not just 3.0.

**Comment by benjamingr** [comment]
Yeah, the point of the other (dupe) issue is that it's back compatible, you're likely not going to break 1.x or 2.x anyway and it'd be beneficial to document it since people are already using it when using promises anyway (passing it to Promise.all is pretty common when you want to wait for the page to load _and_ to make an AJAX request for data). 

Thanks for considering. I'd love to use this.

**Comment by benjamingr** [comment]
ping.

**Comment by mnpenner** [comment]
So....does jQuery have a Promise for when the document is ready or not?

**Comment by dmethvin** [comment]
Yes it does. Think of it as a thenable though and to not make other assumptions about it.

https://github.com/jquery/jquery.com/blob/master/pages/upgrade-guide/3.0.md#feature-jqueryready-promise-is-formally-supported

**Comment by AurelioDeRosa** [comment]
Should this be referred as what we'll call [jQuery-Promise](https://github.com/jquery/api.jquery.com/issues/926)?

**Comment by dmethvin** [comment]
No, this is actually just a thenable so we provide even fewer guarantees about what it is. It is acceptable to use `jQuery.ready` as input to `jQuery.when)` but not to do something like `jQuery.ready.done(fn)` because we don't guarantee that it will have a `.done()` method like a `jQuery.Deferred` would have. That's the gist of the upgrade guide explanation too.

Perhaps we could create a `Thenable` type since it would be used to define this property and also for the input type of `jQuery.when()`? Seems like another good thing for @gibson042 input.

**Comment by gibson042** [comment]
> Perhaps we could create a `Thenable` type since it would be used to define this property and also for the input type of `jQuery.when()`?

I like that. In practice, it is a base of both ES6 Promise and jQuery Promise, the latter of which is itself a base of jQuery Deferred.

**Comment by dmethvin** [comment]
See also #906 and #530, there's some duplication among them.
