### ISSUE TITLE
Document the attributes that `attr` normalize

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.jquery.com#422]
On the page for `.attr()` there's a hint at jQuery normalizing "some" attributes:

> The values of some attributes are reported inconsistently across browsers, and even across versions of a single browser. The .attr() method reduces such inconsistencies.

I would like to get a list of attributes that jQuery normalizes in that page, along with details where appropriate.

**Comment by dmethvin** [comment]
We just looked at this, and the situations where we normalize values are to fix obscure browser bugs. We're hesitant to document that because it will inevitably get out of date (either way) over time. On master at the moment, the only attrHook we have is to fix IE9-11 for the case where you change the `type` on an `<input>` and it incorrectly clears the `value` property.

For a complete list of normalized attributes for a specific version, look at `attrHooks` in the source and the corresponding `support` tests.
