### ISSUE TITLE
Is passing a selector to 'contents' supported?

### ISSUE THREAD

**Issue by hesselink** [jquery/api.jquery.com#754]
It's currently possible to pass a selector string to `.contents`. Most selectors never matches text nodes, but it does keep them when you use a ':not' selector or things like "*". This is different from `.contents().filter(selector)`, which always removes text nodes regardless of selector. 

Is this a public feature? It's not documented.

**Comment by gibson042** [comment]
The public API for `.contents` includes only a single signature, and it does not accept an argument because the interaction of text nodes and selectors is undefined (and could even throw exceptions). If you need to filter a collection that might include non-elements, use [`.filter( function )`](http://api.jquery.com/filter/#filter-function).

**Comment by hesselink** [comment]
Thanks, that's what we ended up doing already, just wanted to check.
