### ISSUE TITLE
deferred.always parameters changing based on success?

### ISSUE THREAD

**Issue by axos88** [jquery/api.jquery.com#763]
Hello,

I am reading this on the jquery.ajax documentation page:

```
jqXHR.always(function( data|jqXHR, textStatus, jqXHR|errorThrown ) { });
An alternative construct to the complete callback option, the .always() method replaces the deprecated .complete() method.
```

This is a documentation error or a bad joke, right?
The parameter order changing based on wether the query succeeds or not?

How is one to determine the actual status code without actually knowing if it was successful or not?

**Comment by dcherman** [comment]
I'd recommend treating `always` as a `finally` block, and those blocks never accept arguments in other languages.

To answer your actual question, you could inspect the result of `.state()` on the Promise to see whether or not it was resolved, or you could detect it via the presence of some well-known property on the XHR to see what position in the arguments list it is.

```js
if ( data && data.getResponseHeader ) {
  // Error
} else {
  // Success
}
```

**Comment by axos88** [comment]
Well this is an unfortunate API decision.
Are there any plans to fix this in the next breaking version change?

Btw, I ended up doing this:
```
        function AjaxGetRequest(path, params, cb) {
            $.get(path, params, function(data, a, xhr) { cb(xhr.status, data) }, 'json').error(function(xhr, message) {
                    cb(xhr.status, xhr.responseJSON);
                });
        }
```

**Comment by dmethvin** [comment]
I understand the confusion but this is pretty much impossible to "fix" via code because the standard `deferred.always()` method is defined to accept the args that `.resolve()` or `.reject()` were passed, there's no special set or ordering of args passed to it. I think the best way to handle this as a consumer of `jQuery.Deferred()` is to follow @dcherman's advice and only use `.always()` to do things that are common to both success and failure and don't require the args, such as deallocating resources and the like. That is, don't use it as a catch-all that will try to determine success or failure based on args and do something.

Perhaps we can add something like this to the [deferred.always](http://api.jquery.com/deferred.always/) docs:

> Note that the `deferred.always()` method receives the arguments that were used to `.resolve()` or `.reject()` the deferred, which are often very different. For that reason, it is best to use the `.always()` method only for actions that do not require inspecting the arguments. In all other cases, use explicit `.done()` or `.fail()` handlers since the arguments will have well-known orders.
