### ISSUE TITLE
.css('marginRight') may not be accurate for negative percent margins in Android 4.0-4.3

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#865]
See https://github.com/jquery/jquery/issues/1815

Retrieving negative percent margin-right in Android 4-4.4 may not return expected values. This is unfortunate, but necessary until we drop support for Android 2.3.

**Comment by dmethvin** [comment]
If we have to choose, maybe we should make Android 2.3 lose this contest?

**Comment by AurelioDeRosa** [comment]
I'll wait before submitting a PR for this as it seems there is room for discussion.

**Comment by AurelioDeRosa** [comment]
Any update on this issue?

**Comment by AurelioDeRosa** [comment]
Friendly ping @dmethvin and @timmywil.

**Comment by mgol** [comment]
@timmywil it's Android 4.0-4.3, not 4.4. Android 4.4 doesn't have the Android Browser.

Also, I think you confused the issue a little - it's not Android 2.3 that's the problem here. There's a bug in Android 4.0-4.3 only: `getComputedStyle` sometimes returns percents instead of the pixel value for some values. The workaround for this bug causes the issue with negative percent margins but we decided that's a lesser evil, especially that it worked like that for a long time.

This issue is valid, it's something we need to document for Android 4.0-4.3.

**Comment by mgol** [comment]
This is my PR that fixes the percent-instead-of-pixel bug in Android 4.0-4.3 but causes the one we need to document here: https://github.com/jquery/jquery/pull/1842.

**Comment by dmethvin** [comment]
Is this something we should even attempt to document?

**Comment by mgol** [comment]
@dmethvin always asking the difficult questions! :smile:

Probably not too many people care about negative percent margins in Android 4.0-4.3. But we don't seem to have many such bugs accepted in various browsers, do we? We might as well document it, at least at https://contribute.jquery.org/wont-fix/.

**Comment by dmethvin** [comment]
That does sound like a better fit for wont-fix I think. Also, with Google and StaclOverflow I think it is legit to have comments like these act as documentation. We can't have yellow-box warnings sprinkled around every API call for each quirk of particular browsers, and this is an obscure one.

So basically the wont-fix text is something like?

> Negative margins on Android 4.0-4.3 browser: These browsers return incorrect values from the DOM `getComputedStyle` method which causes jQuery to return the wrong value.

**Comment by mgol** [comment]
@dmethvin Sounds good. And good points. :+1:

**Comment by AurelioDeRosa** [comment]
This issue has been documented in the contribute website. Closing.
