### ISSUE TITLE
Document that $('.foo').append(document.createTextNode('bar')) is a supported use case

### ISSUE THREAD

**Issue by stanvass** [jquery/api.jquery.com#879]
The documentation says append() accepts:

- string
- Element
- jQuery collection

The problem is there's no official way to append a text *node* in jQuery. Using append() with a text node works just fine, but Text is not an instance of Element, it's an instance of its parent prototype, Node.

The way this is documented echoes in other tools and definitions like Definitely Typed's jQuery TypeScript .d.ts definition, where the TypeScript compiler throws an error when I'm appending a text node.

Please fix this in the documentation so it can trickle downstream into our tooling. Thanks :-)

**Comment by dmethvin** [comment]
Yeah, that should be documented (and for `.prepend` etc) since it's been supported forever.

**Comment by kswedberg** [comment]
@dmethvin same for `.before()` and `.after`, too? And when you say "forever," do you mean, like, since 1.0—so we can just add the type to the existing signature? Should the new type be "Text" or "textNode" or "textContent"? Doesn't look like any of them shows up in https://api.jquery.com/Types/, so we'd have to add it there, too, right?

**Comment by timmywil** [comment]
@kswedberg I'd vote for "Text", since that's what's in the spec.

**Comment by kswedberg** [comment]
kthx, @timmywil !

**Comment by dmethvin** [comment]
Yep, since 1.0 since a string is turned into a combination of nodes, some of which can be text nodes. Any API that accepts an arbitrary HTML string should also accept a text node, so that would include `.html()`
