### ISSUE TITLE
Attribute Equals Selector docs may be vague

### ISSUE THREAD

**Issue by ericandrewlewis** [jquery/api.jquery.com#910]
The [Attribute Equals Selector](https://api.jquery.com/attribute-equals-selector/) doc says that the attribute value "Can be either an unquoted single word or a quoted string."

This is a bit vague in light of [jquery/jquery#2824](https://github.com/jquery/jquery/issues/2824#issuecomment-171483952), as `#anchor` needs to be quoted. Perhaps we should just say that the value must be quoted, as describing how `#anchor` is a special case and not a single word seems a bit complex.

**Comment by georgestephanis** [comment]
The w3 attribute selector specification requires that attribute values must be CSS **identifiers **or **strings**. -- https://www.w3.org/TR/css3-selectors/#attribute-selectors

In this context, **identifiers **may be comprised exclusively of case-insensitive alphanumeric characters, hyphens, underscores, and ISO 10646 characters U+00A0 and higher.  As the # sign does not fall under this subset of characters (it's actually U+0023), the attribute value need to use the **string **syntax -- and in this context, strings must always be quoted.

**Comment by dmethvin** [comment]
I think an "unquoted single word" is pretty clear, so `abc` and `dog` are words but `#abc` and `~$&@*` are not. If there is a simpler small phrase we can use there that doesn't require a paragraph let us know. Remember that this definition would need to be repeated anywhere that the identifier/string distinction is present in CSS selectors, including all the attribute selectors and not just this one. The spec's "CSS identifier" isn't that clear unless you follow the link and read the paragraph that describes it. 

The basic problem here is that jQuery first tried the high-performance `querySelectorAll` method, which rightly threw an error. When it used Sizzle to parse the string it got through via a bug and the incorrect selector was allowed, doing what the author intended 99 percent of the time.

So this wording is really all about justifying our right to make an invalid and undocumented case break the way it should have all along. It shouldn't be a problem with new code because people would most likely figure it out quickly.

**Comment by aaronjorbin** [comment]
Unquoted single word on its own isn't necessarily true.  While `#abc` isn't a word, `Ke$ha` is a word (even though she decided to switch to Kesha).

Perhaps "Can be either an unquoted single word (only containing alphanumeric characters) or a quoted string." ?  Makes it clearer what word means.

**Comment by georgestephanis** [comment]
But the spec permits hyphens and underscores as well 🕵

**Comment by dmethvin** [comment]
It was never our intent with this documentation to replace the official spec. To say the exact same thing I suppose we should be using the exact same words in the same quantity, or we could just link to the spec. Nobody really wants to read something that excruciatingly and exhaustively detailed so the best thing to do is quote anything with special characters.

So how about to clarify if we make the phrase "unquoted single word" link to https://www.w3.org/TR/css3-selectors/#attribute-selectors and let people who want to argue semantics read that as their pennance? :smiling_imp:

**Comment by kswedberg** [comment]
Sorry for entering the conversation late, but I thought I'd point out that we already deal with this on the main [Attribute Selectors](http://api.jquery.com/category/selectors/attribute-selectors/) page:

> Attribute values in selector expressions must follow the rules for W3C CSS selectors; in general, that means anything other than a [valid identifier](http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier) should be surrounded by quotation marks.

It then provides a few examples of quoting the attribute values. 

I'd prefer changing "unquoted single word" to "valid identifier" and linking to http://www.w3.org/TR/CSS21/syndata.html#value-def-identifier . And if we want to be really thorough, we could add a `<longdesc>` and say something like "For more information about using attribute selectors, see the [Attribute Selectors](http://api.jquery.com/category/selectors/attribute-selectors/) page." Or, we could create a reusable note to the same effect and add it to every attribute selector, since it applies just as much to the others.

**Comment by dmethvin** [comment]
I certainly defer to the wordsmiths here. Should we just link to our own Attribute Selectors page on these subpages perhaps?

**Comment by AurelioDeRosa** [comment]
I'd vote for having a link to our own doc. Should I submit a PR for this issue?

**Comment by kswedberg** [comment]
Thanks, @aaronjorbin and @AurelioDeRosa . Linking to an explanation is definitely an improvement. I still think "unquoted single word" is imprecise, though, and would prefer to use "valid identifier" instead. Makes sense to drop the "unquoted" bit, too, because there's no harm in quoting a valid identifier (and, in fact, some would prefer to quote it for consistency's sake).

`Can be either a <a href="https://www.w3.org/TR/css3-selectors/#attribute-selectors">valid identifier</a> or a quoted string.`

If there is some agreement, I can make the change. Or, if someone else wants to do it, that's fine, too.

**Comment by kswedberg** [comment]
Oh, and @AurelioDeRosa , I think changing that link from www.w3.org to our own doc is fine.

**Comment by AurelioDeRosa** [comment]
Thinking again about it, I think it's fine to have the link to W3C. Let's see what other think about it.

**Comment by dmethvin** [comment]
Either works for me, I defer to the wordsmiths!

**Comment by AurelioDeRosa** [comment]
I'm pro changing "valid identifier" with "valid identifier". It sounds better and more precise.

**Comment by kswedberg** [comment]
great! @AurelioDeRosa: do you want to take care of the word change, or shall I?

**Comment by AurelioDeRosa** [comment]
If you don't mind, sent a PR and I'll review it (not that you really need it).
