### ISSUE TITLE
.load() method recommended on .ready() page, even though it's deprecated

### ISSUE THREAD

**Issue by xsanda** [jquery/api.jquery.com#964]
In the yellow warning box on http://api.jquery.com/ready/, the `.load()` method is recommended, even though it has been removed in 3.0.0, and was deprecated in 1.8.

**Comment by dmethvin** [comment]
I'll work on rephrasing this, there are several things that need to be clarified.

**Comment by dmethvin** [comment]
Additionally:
* Mention preference for `$(function)`; others are deprecated since they don't use their selection.
* When multiple functions are added, they run in the order they are added.
* As of jQuery 3.0 an error in one function will not prevent subsequent functions from running.
* Do not assume that it is safe to attach document.onload handlers in a ready function.
* Ready functions are guaranteed to run even when loaded long after the document has finished loading; window.onload is not
