### ISSUE TITLE
No documentation of '> ...' selector on .find()

### ISSUE THREAD

**Issue by xsanda** [jquery/api.jquery.com#973]
The function .find() supports selectors starting with a gt sign, >. This means that it will start the selector search with a direct child. This behaviour is, as far as I can see, undocumented.

**Comment by AurelioDeRosa** [comment]
You're right in saying that this is not documented. However, I don't think we should document or encourage it because that is a non-standard selector. In fact, it won't work with `querySelector()`. Any other opinion on this?

**Comment by mgol** [comment]
Leading combinators are perfectly fine and the upcoming `.queryAll` standard, once it finally materializes, will support them natively in browsers.

Using such selectors doesn't preclude the selector from going the `querySelectorAll` path as internally jQuery changes:
```js
elem.find( "> .btn" );
```
to:
```js
document.querySelectorAll( "#a-temporary-id-for-elem > .btn" );
```

I think this issue is valid and we should have it documented somewhere.

**Comment by AurelioDeRosa** [comment]
Cool. I wasn't aware `queryAll()` was going to support such selectors.

**Comment by mgol** [comment]
`querySelectorAll` wasn't able to support them because it runs queries against the whole document and only afterwards filters out everything not contained within the queried context. This is contrary to how jQuery (& most other libraries at the time) selection worked and made selectors with leading combinators impossible - a problem [John Resig complained about in 2008](http://ejohn.org/blog/thoughts-on-queryselectorall/). :)

**Comment by kswedberg** [comment]
@mgol : it looks like `.queryAll()` has been removed from the DOM spec…
http://stackoverflow.com/questions/23269785/whats-the-difference-between-queryall-and-queryselectorall#38245620

**Comment by mgol** [comment]
@kswedberg They have been removed until some details in how it should utilize JS subclassing etc. are resolved. They should be back once all the details are fleshed out (I hope!).

In any case, such selectors in jQuery are perfectly fine and use the fast qSA path so this issue is still valid. :)

**Comment by kswedberg** [comment]
@mgol : yes, I agree about the main issue, of course: these selectors are perfectly fine in jQuery. 👍
